# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XDVerticalGradientColorSlider' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'XDVerticalGradientColorSlider', :path => '.././'
  pod 'Masonry', '~> 1.0.2'
  # Pods for XDVerticalGradientColorSlider

end
